CREATE TABLE IF NOT EXISTS PRODUCTS(
    PRODUCT_ID TEXT PRIMARY KEY,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATAGORY_ID TEXT,
    UNITS TEXT,
    PRICE REAL
);
INSERT INTO PRODUCTS
(PRODUCT_ID,PRODUCT_NAME,SUPPLIER_ID,CATAGORY_ID,UNITS,PRICE)
VALUES
('1','CHAIC','1','1','10BOXES*20BAGS',18.00),
('2','CHANG','1','1','24-12 OZ BOTTLES',19.00),
('3','ANISEED SYRUP','1','2','12-550ml BOTTLE',10.00),
('4','CHEFF ANTANIG SYSENING','2','2','40-6 OZ BOTTLE',22.00),
('5','CHEFF ANTON MIX','2','2','36 BOXES',21.35);

SELECT * FROM PRODUCTS;

SELECT AVG(PRICE) AS AVG_PRICE 
FROM PRODUCTS;


SELECT COUNT(PRODUCT_ID) AS PRODUCT_COUNT
FROM PRODUCTS;

SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCTS;

SELECT MIN(PRICE) AS MIN_PRICE
FROM PRODUCTS;

